version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
      - ITUNES_API_URL=https://itunes.apple.com/search
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - mynetwork

  album-app:
    build:
      context: ./album-app
    ports:
      - "8080:8080" 
    volumes:
      - ./album-app:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend
    networks:
      - mynetwork

networks:
  mynetwork:
